name: Experiment

on: [push, pull_request, workflow_dispatch]

jobs:
  experiment:
    name: Run experiment

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Do the globbing
        run: |
          git check-ignore -vn "XXX/\'" || :
        shell: bash
